site_name: Polyscope 
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'deep orange'
markdown_extensions:
  - codehilite
  - admonition
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.emoji

extra:
  search:
    tokenizer: '[\s\-\.::]+'

extra_css:
  - extras.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

repo_name: 'nmwsharp/polyscope'
repo_url: 'https://github.com/nmwsharp/polyscope'

pages:
  - Home: 'index.md'
  - Install & Build: 
    - 'Basics' : 'building/index.md'
  - Structures: 
    - 'Structure management' : 'structures/structure_management.md'
    - Surface Mesh:
      - 'Indexing Convention' : 'structures/surface_mesh/indexing_convention.md'
      - 'Scalar Quantities' : 'structures/surface_mesh/scalar_quantities.md'
      - 'Vector Quantities' : 'structures/surface_mesh/vector_quantities.md'
    - Point Cloud:
      - 'Scalar Quantities' : 'structures/point_cloud/scalar_quantities.md'
  - Integrations: 
      - 'Geometry Central' : 'integrations/geometry_central/index.md'
      - 'CGAL' : 'integrations/cgal/index.md'
